ASSUME CS:CODESG

DATA SEGMENT
TAB DB 'HELLO WORLD$'
DATA ENDS

CODE SEGMENT
        ASSUME CS:CODE, DS:DATA
START:
        MOV AX,DATA
        MOV DS,AX
        LEA DX,TAB
        MOV AH,9H
        INT 21H
        MOV AH,4CH
        INT 21H
CODE  ENDS
END START

